apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: url-mongo
spec:
  selector:
    matchLabels:
      app: url-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: url-mongo
    spec:
      containers:
      - name: url-mongo
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
            - configMapRef:
                name: url-mongo-config
        volumeMounts:
            - mountPath: /var/lib/mongo/
              name: url-mongo                
      volumes:
        - name: url-mongo
          persistentVolumeClaim:
            claimName: url-mongo-disk   
