apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: url-redis
  name: url-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: url-redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: ""
        name: url-redis
        resources: {}
      hostname: url-redis
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
